{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 1\n  +2\n  -1", "trace": "self = <test_pytest.Test3 object at 0x000001AC56BBFF40>\n\n    @allure.story(\"cs2\")\n    def test_2(self):\n>       assert 2==1\nE       assert 2 == 1\nE         +2\nE         -1\n\ntest_pytest.py:29: AssertionError"}, "start": 1640099971011, "stop": 1640099971011, "uuid": "fac8d5f2-3502-4eb9-9322-fd4c10ce79e8", "historyId": "9aa6e0afcb84c1672715b50dc8bf4d84", "testCaseId": "4c061a7eea26c5838d88aaf9024b3072", "fullName": "test_pytest.Test3#test_2", "labels": [{"name": "story", "value": "cs2"}, {"name": "feature", "value": "aaa页面"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Test3"}, {"name": "host", "value": "zhou"}, {"name": "thread", "value": "5708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest"}]}